name: Docbuild

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Set up Python"
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install doc dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install pandoc
        pip install -r examples/requirements.txt
    - name: Build docs
      run: |
        cd docs
        sphinx-build -W docs/source docs/build